book/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/flight', "FlightController");

Route::resource('/departments', 'DepartmentController');

Route::resource('/director','DirectorController');

Route::resource('/studentdata','StudentdataController');

Route::resource('/teacher','TeacherController');

Route::resource('/match','DistributionchoseController');

Route::resource('/nomatch','DistributionnotchoseController');

Route::resource('/matchnum','MatchNumController');

Route::get('users/{id}', function ($id) {

});

book/app/department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class department extends Model
{
    //
    protected $table="departments";
    protected $fillable = ['name','department'];
}

book/app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\department;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $departments= department::all();
        return json_encode($departments);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

book/resources/views/Department/Exceltest.blade.php
<form method="post" action="{{ route('iptOfDepartment') }}" enctype="multipart/form-data">
    {{ csrf_field() }}
    <br>
    <input type="file" name="select_file" id="input"/>
    <input type="submit" name="upload" />
</form>

book/resources/views/Department/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>系務辦公室</title>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
            rel="icon"
            href="https://www.nuu.edu.tw/var/file/0/1000/msys_1000_9991812_60080.jpg"
            type="image/x-icon"
    />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
    />
    <link
            href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap"
            rel="stylesheet"
    />
    <style>
        * {
            font-family: "Noto Sans TC", sans-serif;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/flight">系務辦公室</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars" aria-hidden="true"></i> </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{{route('director.index')}}">建立主任資料</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">匯入學生資料</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">匯入評審委員資料</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">分配評分人員</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">評分項目與分數區間</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">查看所有老師評分細節</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Button trigger modal -->

<!-- Modal -->

<section class="mt-5" id="app">
    @yield('content')
</section>

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.0/axios.js"></script>
    <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
    ></script>
@show
</body>
</html>

book/resources/views/Department/match.blade.php
@extends('Department.header')
@section('content')
<section class="mt-5" id="app">
    <div class="container">
        <div class="row">
            <form action="{{route('matchnum.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="">請輸入學生需要幾位老師評分</label>
                    <input type="text" name="id" id="" class="form-control" placeholder="" aria-describedby="helpId">
                    <small id="helpId" class="text-muted">第一次輸入後按下確定 資料庫產生資料 <span style="color:#ff0000;">若想更改人數 資料庫不保留以選擇人員</span></small>
                </div>
                <button type="submit" name="" id="" class="btn btn-primary">送出</button>
            </form>
            <form action="{{ route('matchnum.store', 0) }}" method="post">

                @csrf
                <input type="hidden" name="id" value="4" />

                <button type="submit" name="" id="" class="btn btn-danger">
                    POST
                </button>
            </form>
        </div>
    </div>

    <div class="container mt-3">
        <div class="row">
            <div class="col-12" v-if="!first">
                <div class="card text-center">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs">
                            <li class="nav-item">
                                <a class="nav-link" :class="{active : nowselected }" @click="nowselected=1"
                                    href="#">未選擇</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" :class="{active : !nowselected }" @click="nowselected=0"
                                    href="#">已選擇</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body" >
                        <div class="row">
                            <div class="col-2 d-flex flex-column">
                                <template v-for="(item, index) in theacher">
                                    <button type="button" name="" id="" class="btn p-2 m-2 "
                                        :class="{ btnPrimary: index == nowteacher }" @click="changeTeacher(index)">
                                        @{{item}}</button>
                                </template>
                            </div>
                            <div class="col " v-if="nowselected">
                                <form action="">
                                    <div class="row h-100">
                                        <div class="col-12  d-flex flex-wrap">
                                            <template v-for="(item, index) in theacher">
                                                <template v-for="(item1, index2) in student[index]">
                                                    <div class="form-check"
                                                        :class="{ disable: index != nowteacher }">
                                                        <input type="text"  name="" id="" :value="item">
                                                        <label class="form-check-label">
                                                            <input type="checkbox" class="form-check-input"
                                                                name="student" id="" value="checkedValue">
                                                            <i class="fa fa-user fa-4x " aria-hidden="true"
                                                                :style=""></i>
                                                            @{{item1}}
                                                        </label>
                                                    </div>
                                                </template>
                                            </template>
                                        </div>
                                    </div>
                                    <div class="row mt-5">
                                        <div class="col-12">
                                            <div>
                                                <button type="button" name="" id=""
                                                    class="btn btn-primary">送出</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col d-flex flex-wrap" v-else>
                                <template v-for="(item, index) in theacher">
                                    <template v-for="(item1, index2) in selected[index]">
                                        <div class="form-check" :class="{ disable: index != nowteacher }">
                                            <label class="form-check-label">
                                                <i class="fa fa-user fa-4x " aria-hidden="true" :style=""></i>
                                                @{{item1}}
                                            </label>
                                        </div>
                                    </template>
                                </template>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection
@section('script')
    @parent
    <script>
        new Vue({
            el: "#app",
            data() {
                return {
                    theacher: ['1', '2', '3', '4'],
                    student: [],
                    selected: [],
                    nowteacher: 0,
                    nowselected: 1,
                    first:true
                }
            },
            methods: {
                changeTeacher(index) {
                    this.nowteacher = index;
                }
            },
            created() {
                // for (let i = 0; i < this.theacher.length; i++) {
                //     this.student[i] = new Array();
                //     for (let j = 0; j < 20 + i; j++) {
                //         this.student[i][j] = j + 1;
                //     }
                // }
                // for (let i = 0; i < this.theacher.length; i++) {
                //     this.selected[i] = new Array();
                //     for (let j = 0; j < 3 + i; j++) {
                //         this.selected[i][j] = j + 1;
                //     }
                // }
                // console.log(this.student);
                axios.get("http://book.test/matchnum/show").then(res=>{
                    if (res.data.length!=0){
                        first=true;
                    } else {
                        first=false;
                    }
                })
            },
        })
    </script>
@endsection

book/resources/views/Department/student.blade.php
@extends('Department.header') @section('content')
<section class="mt-5" id="app">
  <div
    class="modal fade"
    id="InputForExcel"
    tabindex="-1"
    role="dialog"
    aria-labelledby="modelTitleId"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">匯入</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <input
          type="file"
          id="ExcelAdd"
          style="display: none"
          @change="fileChange()"
          accept=".xlsx, .xls, .csv"
        />
        <input
          type="file"
          id="ExcelUpdate"
          style="display: none"
          @change="fileChange2()"
          accept=".xlsx, .xls, .csv"
        />
        <div class="modal-body">
          <div class="container">
            <div class="row my-2">
              <button class="btn btn-success" onclick="$('#ExcelAdd').click()">
                新增
              </button>
              <span class="m-2">新增資料在原本資料後方，不會將原資料刪除</span>
            </div>
            <div class="row my-2">
              <button
                class="btn btn-primary"
                onclick="$('#ExcelUpdate').click()"
              >
                更新
              </button>
              <span class="m-2">取代原本資料，不會保留原有資料</span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            關閉
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div
    class="modal fade"
    id="changeinput"
    tabindex="-1"
    role="dialog"
    aria-labelledby="modelTitleId"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">修改學生資料</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{{ route('studentdata.update', 0) }}" method="post">
            <input type="hidden" name="_method" value="PUT" />
            <input type="hidden" name="id" v-model="change.id" />
            @csrf
            <div class="container">
              <div class="row">
                <div class="form-group">
                  <label for="">准考證號碼</label>
                  <input
                    type="text"
                    name="account"
                    id=""
                    class="form-control"
                    placeholder=""
                    aria-describedby="helpId"
                    v-model="change.account"
                    required
                  />
                  <small id="helpId" class="text-muted">輸入准考證號碼</small>
                </div>
              </div>
              <div class="row">
                <div class="form-group">
                  <label for="">姓名</label>
                  <input
                    type="text"
                    name="name"
                    id=""
                    class="form-control"
                    placeholder=""
                    aria-describedby="helpId"
                    v-model="change.name"
                  />
                  <small id="helpId" class="text-muted">輸入名稱</small>
                </div>
              </div>
              <div class="row">
                <div class="form-group">
                  <label for="">有效日期</label>
                  <input
                    type="date"
                    name="date"
                    id=""
                    class="form-control"
                    placeholder=""
                    aria-describedby="helpId"
                    v-model="change.date"
                    required
                  />
                  <small id="helpId" class="text-muted">選擇有效日期</small>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
                @click="CloseInput"
              >
                關閉
              </button>
              <button type="submit" class="btn btn-primary">儲存</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="container" v-if="loading">
    <div class="row">
      <div class="col-12">
        <button
          type="button"
          name=""
          id=""
          class="btn btn-primary mx-2"
          data-toggle="modal"
          data-target="#InputForExcel"
        >
          匯入學生資料
        </button>
      </div>
      <table class="table mt-2">
        <thead>
          <tr>
            <th>編號</th>
            <th>准考證號碼</th>
            <th>姓名</th>
            <th>部門</th>
            <th>有效日期</th>
            <th>修改</th>
            <th>刪除</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(item,index) in all">
            <td scope="row">@{{ index + 1 }}</td>
            <td>@{{ item.account }}</td>
            <td>@{{ item.name }}</td>
            <td>@{{ item.department }}</td>
            <td>@{{ item.date }}</td>
            <td>
              <button
                type="button"
                name=""
                id=""
                class="btn btn-info"
                @click="changedata(index)"
              >
                修改
              </button>
            </td>
            <td>
              <form action="{{ route('studentdata.destroy', 0) }}" method="post">
                <input type="hidden" name="_method" value="DELETE" />
                @csrf
                <input type="hidden" name="id" v-model="item.id" />
                <button type="submit" name="" id="" class="btn btn-danger">
                  刪除
                </button>
              </form>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div v-else class="container"><h1>loading</h1></div>
</section>

@endsection @section('script') @parent
<script>
  new Vue({
    el: "#app",
    data() {
      return {
        loading: false,
        type: {
          name: "",
          account: "",
          department: "",
          date: ""
        },
        change: {
          id: 0,
          name: "",
          account: "",
          department: "",
          date: ""
        },
        all: [],
        departments: []
      };
    },
    methods: {
      changedata(index) {
        this.change.id = this.all[index].id;
        this.change.name = this.all[index].name;
        this.change.account = this.all[index].account;
        this.change.department = this.all[index].department;
        this.change.date = this.all[index].date;
        $("#changeinput").modal("show");
      },
      CloseInput() {
        console.log("close");
        this.type.name = "";
        this.type.account = "";
        this.type.department = "";
        this.type.date = "";
        $("#TypingInput").modal("hide");
      }
    },
    created() {
      this.loading = false;
      axios.get("http://127.0.0.1:8000/studentdata/show").then(res => {
        this.all = res.data;
        this.loading = true;
      });
    }
  });
</script>
@endsection

book/resources/views/Department/teacher.blade.php
@extends('Department.header') @section('content')
<section class="mt-5" id="app">
  <div
    class="modal fade"
    id="InputForExcel"
    tabindex="-1"
    role="dialog"
    aria-labelledby="modelTitleId"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">匯入</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <input
          type="file"
          id="ExcelAdd"
          style="display: none"
          @change="fileChange()"
          accept=".xlsx, .xls, .csv"
        />
        <input
          type="file"
          id="ExcelUpdate"
          style="display: none"
          @change="fileChange2()"
          accept=".xlsx, .xls, .csv"
        />
        <div class="modal-body">
          <div class="container">
            <div class="row my-2">
              <button class="btn btn-success" onclick="$('#ExcelAdd').click()">
                新增
              </button>
              <span class="m-2">新增資料在原本資料後方，不會將原資料刪除</span>
            </div>
            <div class="row my-2">
              <button
                class="btn btn-primary"
                onclick="$('#ExcelUpdate').click()"
              >
                更新
              </button>
              <span class="m-2">取代原本資料，不會保留原有資料</span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            關閉
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div
    class="modal fade"
    id="changeinput"
    tabindex="-1"
    role="dialog"
    aria-labelledby="modelTitleId"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">修改老師資料</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{{ route('teacher.update', 0) }}" method="post">
            <input type="hidden" name="_method" value="PUT" />
            <input type="hidden" name="id" v-model="change.id" />
            @csrf
            <div class="container">
              <div class="row">
                <div class="form-group">
                  <label for="">帳號</label>
                  <input
                    type="text"
                    name="account"
                    id=""
                    class="form-control"
                    placeholder=""
                    aria-describedby="helpId"
                    v-model="change.account"
                    required
                  />
                  <small id="helpId" class="text-muted">輸入學校帳號</small>
                </div>
              </div>
              <div class="row">
                <div class="form-group">
                  <label for="">姓名</label>
                  <input
                    type="text"
                    name="name"
                    id=""
                    class="form-control"
                    placeholder=""
                    aria-describedby="helpId"
                    v-model="change.name"
                  />
                  <small id="helpId" class="text-muted">輸入名稱</small>
                </div>
              </div>
              <div class="row">
                <div class="form-group">
                  <label for="">有效日期</label>
                  <input
                    type="date"
                    name="date"
                    id=""
                    class="form-control"
                    placeholder=""
                    aria-describedby="helpId"
                    v-model="change.date"
                    required
                  />
                  <small id="helpId" class="text-muted">選擇有效日期</small>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
                @click="CloseInput"
              >
                關閉
              </button>
              <button type="submit" class="btn btn-primary">儲存</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="container" v-if="loading">
    <div class="row">
      <div class="col-12">
        <button
          type="button"
          name=""
          id=""
          class="btn btn-primary mx-2"
          data-toggle="modal"
          data-target="#InputForExcel"
        >
          匯入老師資料
        </button>
      </div>
      <table class="table mt-2">
        <thead>
          <tr>
            <th>編號</th>
            <th>帳號</th>
            <th>姓名</th>
            <th>部門</th>
            <th>有效日期</th>
            <th>修改</th>
            <th>刪除</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(item,index) in all">
            <td scope="row">@{{ index + 1 }}</td>
            <td>@{{ item.account }}</td>
            <td>@{{ item.name }}</td>
            <td>@{{ item.department }}</td>
            <td>@{{ item.date }}</td>
            <td>
              <button
                type="button"
                name=""
                id=""
                class="btn btn-info"
                @click="changedata(index)"
              >
                修改
              </button>
            </td>
            <td>
              <form action="{{ route('teacher.destroy', 0) }}" method="post">
                <input type="hidden" name="_method" value="DELETE" />
                @csrf
                <input type="hidden" name="id" v-model="item.id" />
                <button type="submit" name="" id="" class="btn btn-danger">
                  刪除
                </button>
              </form>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div v-else class="container"><h1>loading</h1></div>
</section>

@endsection @section('script') @parent
<script>
  new Vue({
    el: "#app",
    data() {
      return {
        loading: false,
        type: {
          name: "",
          account: "",
          department: "",
          date: ""
        },
        change: {
          id: 0,
          name: "",
          account: "",
          department: "",
          date: ""
        },
        all: [],
        departments: []
      };
    },
    methods: {
      changedata(index) {
        this.change.id = this.all[index].id;
        this.change.name = this.all[index].name;
        this.change.account = this.all[index].account;
        this.change.department = this.all[index].department;
        this.change.date = this.all[index].date;
        $("#changeinput").modal("show");
      },
      CloseInput() {
        console.log("close");
        this.type.name = "";
        this.type.account = "";
        this.type.department = "";
        this.type.date = "";
        $("#TypingInput").modal("hide");
      }
    },
    created() {
      this.loading = false;
      axios.get("http://127.0.0.1:8000/teacher/show").then(res => {
        this.all = res.data;
        this.loading = true;
      });
    }
  });
</script>
@endsection